require "sdl-crystal-bindings"
require "sdl-crystal-bindings/sdl-mixer-bindings"
require "sdl-crystal-bindings/sdl-image-bindings"
require "sdl-crystal-bindings/sdl-ttf-bindings"

require "./base/Collishi.cr"
require "./base/CollisionShapes.cr"
require "./base/Coords.cr"
require "./base/Helper.cr"
require "./base/Limiter.cr"
require "./base/Main.cr"
require "./base/Rect.cr"
require "./base/Scene.cr"

require "./audio/Music.cr"
require "./audio/Sound.cr"

require "./input/Event.cr"
require "./input/Keyboard.cr"
require "./input/Mouse.cr"

require "./graphics/Color.cr"
require "./graphics/Drawable.cr"
require "./graphics/Font.cr"
require "./graphics/Map.cr"
require "./graphics/Renderer.cr"
require "./graphics/RenderQueue.cr"
require "./graphics/Shapes.cr"
require "./graphics/Sprite.cr"
require "./graphics/Text.cr"
require "./graphics/Texture.cr"
require "./graphics/View.cr"
require "./graphics/Window.cr"
